/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-08 at 14:07:29 UTC 
 * Modify at your own risk.
 */

package com.example.treasurehunt.gameendpoint;

/**
 * Service definition for Gameendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GameendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Gameendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://treasurehuntandroid.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gameendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Gameendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Gameendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getGame".
   *
   * This request holds the parameters needed by the the gameendpoint server.  After setting any
   * optional parameters, call the {@link GetGame#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetGame getGame(java.lang.String id) throws java.io.IOException {
    GetGame result = new GetGame(id);
    initialize(result);
    return result;
  }

  public class GetGame extends GameendpointRequest<com.example.treasurehunt.gameendpoint.model.Game> {

    private static final String REST_PATH = "game/{id}";

    /**
     * Create a request for the method "getGame".
     *
     * This request holds the parameters needed by the the gameendpoint server.  After setting any
     * optional parameters, call the {@link GetGame#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetGame#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetGame(java.lang.String id) {
      super(Gameendpoint.this, "GET", REST_PATH, null, com.example.treasurehunt.gameendpoint.model.Game.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGame setAlt(java.lang.String alt) {
      return (GetGame) super.setAlt(alt);
    }

    @Override
    public GetGame setFields(java.lang.String fields) {
      return (GetGame) super.setFields(fields);
    }

    @Override
    public GetGame setKey(java.lang.String key) {
      return (GetGame) super.setKey(key);
    }

    @Override
    public GetGame setOauthToken(java.lang.String oauthToken) {
      return (GetGame) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGame setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGame) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGame setQuotaUser(java.lang.String quotaUser) {
      return (GetGame) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGame setUserIp(java.lang.String userIp) {
      return (GetGame) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetGame setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetGame set(String parameterName, Object value) {
      return (GetGame) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertGame".
   *
   * This request holds the parameters needed by the the gameendpoint server.  After setting any
   * optional parameters, call the {@link InsertGame#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.example.treasurehunt.gameendpoint.model.Game}
   * @return the request
   */
  public InsertGame insertGame(com.example.treasurehunt.gameendpoint.model.Game content) throws java.io.IOException {
    InsertGame result = new InsertGame(content);
    initialize(result);
    return result;
  }

  public class InsertGame extends GameendpointRequest<com.example.treasurehunt.gameendpoint.model.Game> {

    private static final String REST_PATH = "game";

    /**
     * Create a request for the method "insertGame".
     *
     * This request holds the parameters needed by the the gameendpoint server.  After setting any
     * optional parameters, call the {@link InsertGame#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertGame#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.treasurehunt.gameendpoint.model.Game}
     * @since 1.13
     */
    protected InsertGame(com.example.treasurehunt.gameendpoint.model.Game content) {
      super(Gameendpoint.this, "POST", REST_PATH, content, com.example.treasurehunt.gameendpoint.model.Game.class);
    }

    @Override
    public InsertGame setAlt(java.lang.String alt) {
      return (InsertGame) super.setAlt(alt);
    }

    @Override
    public InsertGame setFields(java.lang.String fields) {
      return (InsertGame) super.setFields(fields);
    }

    @Override
    public InsertGame setKey(java.lang.String key) {
      return (InsertGame) super.setKey(key);
    }

    @Override
    public InsertGame setOauthToken(java.lang.String oauthToken) {
      return (InsertGame) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertGame setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertGame) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertGame setQuotaUser(java.lang.String quotaUser) {
      return (InsertGame) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertGame setUserIp(java.lang.String userIp) {
      return (InsertGame) super.setUserIp(userIp);
    }

    @Override
    public InsertGame set(String parameterName, Object value) {
      return (InsertGame) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listGame".
   *
   * This request holds the parameters needed by the the gameendpoint server.  After setting any
   * optional parameters, call the {@link ListGame#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListGame listGame() throws java.io.IOException {
    ListGame result = new ListGame();
    initialize(result);
    return result;
  }

  public class ListGame extends GameendpointRequest<com.example.treasurehunt.gameendpoint.model.CollectionResponseGame> {

    private static final String REST_PATH = "game";

    /**
     * Create a request for the method "listGame".
     *
     * This request holds the parameters needed by the the gameendpoint server.  After setting any
     * optional parameters, call the {@link ListGame#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListGame#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListGame() {
      super(Gameendpoint.this, "GET", REST_PATH, null, com.example.treasurehunt.gameendpoint.model.CollectionResponseGame.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListGame setAlt(java.lang.String alt) {
      return (ListGame) super.setAlt(alt);
    }

    @Override
    public ListGame setFields(java.lang.String fields) {
      return (ListGame) super.setFields(fields);
    }

    @Override
    public ListGame setKey(java.lang.String key) {
      return (ListGame) super.setKey(key);
    }

    @Override
    public ListGame setOauthToken(java.lang.String oauthToken) {
      return (ListGame) super.setOauthToken(oauthToken);
    }

    @Override
    public ListGame setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListGame) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListGame setQuotaUser(java.lang.String quotaUser) {
      return (ListGame) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListGame setUserIp(java.lang.String userIp) {
      return (ListGame) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListGame setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListGame setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListGame set(String parameterName, Object value) {
      return (ListGame) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeGame".
   *
   * This request holds the parameters needed by the the gameendpoint server.  After setting any
   * optional parameters, call the {@link RemoveGame#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveGame removeGame(java.lang.String id) throws java.io.IOException {
    RemoveGame result = new RemoveGame(id);
    initialize(result);
    return result;
  }

  public class RemoveGame extends GameendpointRequest<com.example.treasurehunt.gameendpoint.model.Game> {

    private static final String REST_PATH = "game/{id}";

    /**
     * Create a request for the method "removeGame".
     *
     * This request holds the parameters needed by the the gameendpoint server.  After setting any
     * optional parameters, call the {@link RemoveGame#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveGame#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveGame(java.lang.String id) {
      super(Gameendpoint.this, "DELETE", REST_PATH, null, com.example.treasurehunt.gameendpoint.model.Game.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveGame setAlt(java.lang.String alt) {
      return (RemoveGame) super.setAlt(alt);
    }

    @Override
    public RemoveGame setFields(java.lang.String fields) {
      return (RemoveGame) super.setFields(fields);
    }

    @Override
    public RemoveGame setKey(java.lang.String key) {
      return (RemoveGame) super.setKey(key);
    }

    @Override
    public RemoveGame setOauthToken(java.lang.String oauthToken) {
      return (RemoveGame) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveGame setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveGame) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveGame setQuotaUser(java.lang.String quotaUser) {
      return (RemoveGame) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveGame setUserIp(java.lang.String userIp) {
      return (RemoveGame) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveGame setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveGame set(String parameterName, Object value) {
      return (RemoveGame) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateGame".
   *
   * This request holds the parameters needed by the the gameendpoint server.  After setting any
   * optional parameters, call the {@link UpdateGame#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.example.treasurehunt.gameendpoint.model.Game}
   * @return the request
   */
  public UpdateGame updateGame(com.example.treasurehunt.gameendpoint.model.Game content) throws java.io.IOException {
    UpdateGame result = new UpdateGame(content);
    initialize(result);
    return result;
  }

  public class UpdateGame extends GameendpointRequest<com.example.treasurehunt.gameendpoint.model.Game> {

    private static final String REST_PATH = "game";

    /**
     * Create a request for the method "updateGame".
     *
     * This request holds the parameters needed by the the gameendpoint server.  After setting any
     * optional parameters, call the {@link UpdateGame#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateGame#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.treasurehunt.gameendpoint.model.Game}
     * @since 1.13
     */
    protected UpdateGame(com.example.treasurehunt.gameendpoint.model.Game content) {
      super(Gameendpoint.this, "PUT", REST_PATH, content, com.example.treasurehunt.gameendpoint.model.Game.class);
    }

    @Override
    public UpdateGame setAlt(java.lang.String alt) {
      return (UpdateGame) super.setAlt(alt);
    }

    @Override
    public UpdateGame setFields(java.lang.String fields) {
      return (UpdateGame) super.setFields(fields);
    }

    @Override
    public UpdateGame setKey(java.lang.String key) {
      return (UpdateGame) super.setKey(key);
    }

    @Override
    public UpdateGame setOauthToken(java.lang.String oauthToken) {
      return (UpdateGame) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateGame setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateGame) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateGame setQuotaUser(java.lang.String quotaUser) {
      return (UpdateGame) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateGame setUserIp(java.lang.String userIp) {
      return (UpdateGame) super.setUserIp(userIp);
    }

    @Override
    public UpdateGame set(String parameterName, Object value) {
      return (UpdateGame) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Gameendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Gameendpoint}. */
    @Override
    public Gameendpoint build() {
      return new Gameendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GameendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGameendpointRequestInitializer(
        GameendpointRequestInitializer gameendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gameendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
